services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=seustockdb'
      - 'POSTGRES_PASSWORD=seustockpass'
      - 'POSTGRES_USER=seustockuser'
    ports:
      - '5433:5432'
