spring.application.name=SeuStock

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.seu.seustock.model.dto
mybatis.configuration.map-underscore-to-camel-case=true
