CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         NOT NULL DEFAULT RANDOM_UUID(),
    username    VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS spaces (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         NOT NULL DEFAULT RANDOM_UUID(),
    user_id     BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS shelves (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         NOT NULL DEFAULT RANDOM_UUID(),
    space_id    BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (space_id) REFERENCES spaces(id)
);

CREATE TABLE IF NOT EXISTS boxes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         NOT NULL DEFAULT RANDOM_UUID(),
    shelf_id    BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shelf_id) REFERENCES shelves(id)
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         NOT NULL DEFAULT RANDOM_UUID(),
    user_id     BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS stocks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         NOT NULL DEFAULT RANDOM_UUID(),
    item_id     BIGINT       NOT NULL,
    space_id    BIGINT       NOT NULL,
    shelf_id    BIGINT,
    box_id      BIGINT,
    quantity    INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id)  REFERENCES items(id),
    FOREIGN KEY (space_id) REFERENCES spaces(id),
    FOREIGN KEY (shelf_id) REFERENCES shelves(id),
    FOREIGN KEY (box_id)   REFERENCES boxes(id),
    CHECK (quantity >= 0)
);

CREATE TABLE IF NOT EXISTS stock_transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id      UUID         NOT NULL DEFAULT RANDOM_UUID(),
    stock_id         BIGINT       NOT NULL,
    transaction_type VARCHAR(255) NOT NULL,
    quantity_delta   INT          NOT NULL,
    memo             TEXT,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (stock_id) REFERENCES stocks(id)
);
