CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    username    VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS spaces (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS shelves (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    space_id    BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (space_id) REFERENCES spaces(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS boxes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    shelf_id    BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shelf_id) REFERENCES shelves(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS stocks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id     UUID      DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    item_id         BIGINT    NOT NULL,
    space_id        BIGINT    NOT NULL,
    shelf_id        BIGINT,
    box_id          BIGINT,
    serial_number   VARCHAR(255),
    lot_number      VARCHAR(255),
    expiration_date DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'IN_STOCK',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id)  REFERENCES items(id),
    FOREIGN KEY (space_id) REFERENCES spaces(id),
    FOREIGN KEY (shelf_id) REFERENCES shelves(id) ON DELETE CASCADE,
    FOREIGN KEY (box_id)   REFERENCES boxes(id)   ON DELETE CASCADE,
    CONSTRAINT chk_box_requires_shelf CHECK (box_id IS NULL OR shelf_id IS NOT NULL),
    CONSTRAINT chk_stock_status CHECK (status IN ('IN_STOCK', 'DISPATCHED', 'LOST', 'DAMAGED', 'DISPOSED'))
);

CREATE TABLE IF NOT EXISTS stock_transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id      UUID        DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    stock_id         BIGINT      NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    memo             TEXT,
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (stock_id) REFERENCES stocks(id) ON DELETE CASCADE,
    CONSTRAINT chk_transaction_type CHECK (transaction_type IN ('IN', 'OUT', 'MOVE', 'ADJUST'))
);

CREATE TABLE IF NOT EXISTS images (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id       UUID         DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    user_id           BIGINT       NOT NULL,
    storage_path      TEXT         NOT NULL,
    original_filename VARCHAR(255),
    content_type      VARCHAR(100),
    size_bytes        BIGINT,
    content_hash      VARCHAR(64),
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_images_user_hash UNIQUE (user_id, content_hash)
);

CREATE TABLE IF NOT EXISTS item_images (
    item_id       BIGINT    NOT NULL,
    image_id      BIGINT    NOT NULL,
    display_order INT       NOT NULL DEFAULT 0,
    is_primary    BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (item_id, image_id),
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_images (
    stock_id      BIGINT    NOT NULL,
    image_id      BIGINT    NOT NULL,
    display_order INT       NOT NULL DEFAULT 0,
    is_primary    BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (stock_id, image_id),
    FOREIGN KEY (stock_id) REFERENCES stocks(id) ON DELETE CASCADE,
    FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE
);
